service: email-providers-lambda

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  sendEmail:
    handler: src/handlers/send-email/handler.sendEmail
    events:
      - http:
          path: email
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript